import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, CheckCircle2, ClipboardCheck, Clock3, FileWarning, FolderKanban, Plus, TrendingUp } from "lucide-react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useLocation } from "wouter";

const COLORS: Record<string, string> = { Haute: "#d6694b", Normale: "#d9a94b", Basse: "#2f826d" };
const FR_NUMBER = new Intl.NumberFormat("fr-FR");
const IGS_LOGO = "/manus-storage/igs-logo-source_05d3b628.png";

function MetricCard({ label, value, hint, icon: Icon, tone = "sage" }: { label: string; value: string | number; hint: string; icon: typeof FolderKanban; tone?: "sage" | "amber" | "coral" | "ink" }) {
  const style = { sage: "bg-[#e8f1ed] text-[#166653]", amber: "bg-[#fbf1d8] text-[#a16608]", coral: "bg-[#fce7e1] text-[#bc4a33]", ink: "bg-[#e8eeec] text-[#173b32]" }[tone];
  return <Card className="border-0 bg-white shadow-[0_10px_28px_rgba(23,54,46,0.06)]"><CardContent className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.13em] text-[#80908b]">{label}</p><p className="mt-3 font-[Georgia] text-3xl font-semibold tracking-tight text-[#15372f]">{value}</p><p className="mt-1.5 text-xs text-[#7c8a86]">{hint}</p></div><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${style}`}><Icon size={19} /></div></div></CardContent></Card>;
}

function DashboardContent() {
  const [, setLocation] = useLocation();
  const { data, isLoading, error } = trpc.dashboard.get.useQuery();
  if (error) return <Card className="border-0 bg-white"><CardContent className="p-10 text-center"><AlertTriangle className="mx-auto text-[#c4543e]" /><h1 className="mt-4 font-[Georgia] text-2xl font-semibold text-[#173b32]">Données indisponibles</h1><p className="mt-2 text-sm text-[#71817b]">{error.message}</p></CardContent></Card>;
  if (isLoading || !data) return <div className="space-y-7"><Skeleton className="h-24 w-full rounded-3xl" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-36 rounded-2xl" />)}</div></div>;
  const { metrics, priority, monthlyEta, quality, clients } = data;
  return <div className="mx-auto max-w-[1540px] space-y-7">
    <section className="relative overflow-hidden rounded-[1.75rem] bg-[#103b32] px-6 py-7 text-white shadow-[0_18px_45px_rgba(14,59,50,0.17)] sm:px-8"><div className="absolute -right-16 -top-24 h-64 w-64 rounded-full border-[30px] border-[#d9a94b]/15" /><div aria-hidden="true" className="pointer-events-none absolute -right-16 -bottom-36 w-[29rem] opacity-[0.22] mix-blend-multiply"><img src={IGS_LOGO} alt="" className="igs-logo-drift w-full" /></div><div className="relative flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#d9a94b]">Centre de commandement</p><h1 className="mt-2 font-[Georgia] text-3xl font-semibold tracking-tight sm:text-4xl">Pilotage des dossiers</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#c6d8d1]">Vision consolidée des opérations transit, douane et régularisations à traiter.</p></div><Button onClick={() => setLocation("/dossiers/nouveau")} className="h-11 rounded-xl bg-[#d9a94b] px-5 text-[#16372f] hover:bg-[#e5ba64]"><Plus className="mr-2" size={17} />Nouveau dossier</Button></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total dossiers" value={FR_NUMBER.format(metrics.total)} hint={`${metrics.regularized} régularisés`} icon={FolderKanban} tone="ink" /><MetricCard label="Taux de régularisation" value={`${metrics.regularizationRate}%`} hint="dossiers complets" icon={CheckCircle2} /><MetricCard label="ETA dépassées" value={FR_NUMBER.format(metrics.overdue)} hint="sans sortie marchandises" icon={AlertTriangle} tone="coral" /><MetricCard label="Retards à régulariser" value={FR_NUMBER.format(metrics.lateToRegularize)} hint="priorité d’intervention" icon={Clock3} tone="amber" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.45fr_0.9fr]">
      <Card className="border-0 bg-white shadow-[0_10px_28px_rgba(23,54,46,0.06)]"><CardContent className="p-5 sm:p-6"><div className="mb-6 flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#82918c]">Planification</p><h2 className="mt-1 font-[Georgia] text-xl font-semibold text-[#15372f]">Répartition mensuelle des ETA</h2></div><Badge className="border-0 bg-[#e8f1ed] text-[#176653]">{metrics.etaInSevenDays} sous 7 jours</Badge></div><div className="h-[250px]">{monthlyEta.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={monthlyEta} margin={{ left: -20, right: 8 }}><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fill: "#7b8a85", fontSize: 12 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{ fill: "#7b8a85", fontSize: 12 }} /><Tooltip cursor={{ fill: "#edf4f0" }} contentStyle={{ borderRadius: 12, border: "1px solid #e5ece8", boxShadow: "0 8px 20px rgba(15,55,45,0.1)" }} /><Bar dataKey="value" name="Dossiers" fill="#1d7764" radius={[7, 7, 0, 0]} barSize={34} /></BarChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-sm text-muted-foreground">Aucune ETA renseignée.</div>}</div></CardContent></Card>
      <Card className="border-0 bg-white shadow-[0_10px_28px_rgba(23,54,46,0.06)]"><CardContent className="p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#82918c]">Niveau d’attention</p><h2 className="mt-1 font-[Georgia] text-xl font-semibold text-[#15372f]">Répartition par priorité</h2><div className="mt-2 h-[186px]">{priority.some(item => item.value) ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={priority} dataKey="value" nameKey="label" innerRadius={48} outerRadius={70} paddingAngle={4}>{priority.map(item => <Cell key={item.label} fill={COLORS[item.label]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer> : null}</div><div className="grid grid-cols-3 gap-2">{priority.map(item => <div key={item.label} className="rounded-xl bg-[#f6f8f7] px-2 py-2 text-center"><span className="mx-auto mb-1 block h-2 w-2 rounded-full" style={{ backgroundColor: COLORS[item.label] }} /><p className="text-lg font-semibold text-[#15372f]">{item.value}</p><p className="text-[10px] text-[#7a8984]">{item.label}</p></div>)}</div></CardContent></Card>
    </section>
    <section className="grid gap-5 xl:grid-cols-[1.25fr_1fr]">
      <Card className="border-0 bg-white shadow-[0_10px_28px_rgba(23,54,46,0.06)]"><CardContent className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#82918c]">Contrôles qualité</p><h2 className="mt-1 font-[Georgia] text-xl font-semibold text-[#15372f]">Points de vigilance</h2></div><button onClick={() => setLocation("/controles")} className="text-xs font-semibold text-[#1d7764] hover:underline">Tout afficher</button></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{[{ label: "Dossiers incomplets", value: quality.incomplete, icon: FileWarning }, { label: "BL / LTA en doublon", value: quality.duplicateBlLta, icon: ClipboardCheck }, { label: "Déclarations manquantes", value: quality.missingDeclarations, icon: AlertTriangle }, { label: "Sorties non renseignées", value: quality.missingRelease, icon: Clock3 }].map(item => <div key={item.label} className="flex items-center gap-3 rounded-xl border border-[#edf1ef] p-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#fff2ed] text-[#c75842]"><item.icon size={17} /></div><div><p className="text-lg font-semibold text-[#183b33]">{item.value}</p><p className="text-xs text-[#72817c]">{item.label}</p></div></div>)}</div></CardContent></Card>
      <Card className="border-0 bg-white shadow-[0_10px_28px_rgba(23,54,46,0.06)]"><CardContent className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#82918c]">Performance clients</p><h2 className="mt-1 font-[Georgia] text-xl font-semibold text-[#15372f]">Dossiers à régulariser</h2></div><TrendingUp className="text-[#1d7764]" size={20} /></div><div className="mt-4 space-y-3">{clients.slice(0, 5).map(item => <div key={item.client} className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-[#203e37]">{item.client}</p><p className="text-xs text-[#80908b]">{item.total} dossier{item.total > 1 ? "s" : ""}</p></div><Badge className="border-0 bg-[#fff1ed] text-[#bd5038]">{item.toRegularize} à rég.</Badge></div>)}</div><button onClick={() => setLocation("/dossiers")} className="mt-5 flex items-center gap-1 text-xs font-semibold text-[#1d7764] hover:underline">Analyser les dossiers <ArrowRight size={14} /></button></CardContent></Card>
    </section>
  </div>;
}

export default function Home() { return <DashboardLayout><DashboardContent /></DashboardLayout>; }
